drop table if exists public.cases_master;

create table public.cases_master (
    id text primary key,
    ownerMechanism text,
    caseName text,
    country text,
    typeOfRequester text,
    representation text,
    confidentiality text,
    caseURL text,
    projectName text,
    sector text,
    approvalDate date,
    typeOfInvestment text,
    environmentalCategory text,
    typeOfLending text,
    otherLenders text,
    projectStatus text,
    projectCountry text,
    clientName text,
    receptionDate date,
    eligibilityDate date,
    impactSocial boolean default false,
    impactCultural boolean default false,
    impactLivelihoods boolean default false,
    impactEquity boolean default false,
    impactHealth boolean default false,
    impactLabour boolean default false,
    impactEnvironmental boolean default false,
    impactProperty boolean default false,
    impactViolence boolean default false,
    impactStakeholderEngagement boolean default false,
    impactUnclassified boolean default false
);